name: Publish Ubuntu release
on:
  push:
    tags:
      - "v*"

jobs:
  build-for-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      - name: Negotiate Python package hell
        run: |
          sed -i '/python-magic-bin/d' requirements-prod.txt

      - name: Set up build environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements-prod.txt -r requirements-build.txt

      - name: Build for Ubuntu
        run: |
          source venv/bin/activate
          python3 -m PyInstaller -n weatherdl --onefile --add-data "venv/lib/*/site-packages/pptx/templates:pptx/templates" src/main.py

      - name: Copy config files
        run: |
          cp config.json dist

      - name: Produce artifacts
        run: |
          zip weatherdl-for-ubuntu.zip dist/*

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: weatherdl-for-ubuntu.zip
          asset_name: weatherdl-for-ubuntu.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
