name: Publish MacOS release
on:
  push:
    tags:
      - "v*"

jobs:
  build-for-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Set up build environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements-prod.txt -r requirements-build.txt

      - name: Build for MacOS
        run: |
          source venv/bin/activate
          python3 -m PyInstaller -n weatherdl --onefile --add-data "venv/lib/*/site-packages/pptx/templates:pptx/templates" src/main.py

      - name: Copy config files
        run: |
          cp config.json dist

      - name: Produce artifacts
        run: |
          zip weatherdl-for-macos.zip dist/*

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref_name }}
          file: weatherdl-for-macos.zip
          asset_name: weatherdl-for-macos.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            [Download for Windows](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-windows.zip)
            [Download for MacOS](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-macos.zip)
            [Download for Ubuntu](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-ubuntu.zip)
