name: Build for Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up build environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install -r requirements-prod.txt -r requirements-build.txt
      - name: Negotiate Python package hell
        run: |
          .\venv\Scripts\Activate.ps1
          python -m pip uninstall -y python-magic-bin

          $url = 'https://files.pythonhosted.org/packages/07/c2/094e3d62b906d952537196603a23aec4bcd7c6126bf80eb14e6f9f4be3a2/python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl'
          $dest = 'python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl'
          Invoke-WebRequest -Uri $url -OutFile $dest

          python -m pip install $dest
      - name: Build for Windows
        run: |
          .\venv\Scripts\Activate.ps1
          python -m PyInstaller src\weatherdl.py
      - name: Copy config files
        run: |
          Copy-Item config.json dist\weatherdl

