# DEPRECATED: This workflow has been replaced by the unified test.yml workflow
# Building and publishing now happens in a single workflow to avoid duplicate builds
# This file is kept for reference and can be deleted after confirming the new workflow works

name: "[DEPRECATED] Publish Ubuntu release"
on:
  # Workflow disabled - remove this comment to re-enable if needed
  workflow_dispatch: # Manual trigger only

jobs:
  build-for-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Negotiate Python package hell
        run: |
          sed -i '/python-magic-bin/d' requirements-prod.txt

      - name: Set up build environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements-prod.txt -r requirements-build.txt

      - name: Build for Ubuntu
        run: |
          source venv/bin/activate
          python3 -m PyInstaller -n weatherdl --onefile --add-data "venv/lib/*/site-packages/pptx/templates:pptx/templates" src/main.py

      - name: Copy config files
        run: |
          cp config.json dist

      - name: Produce artifacts
        run: |
          zip weatherdl-for-ubuntu.zip dist/*

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref_name }}
          file: weatherdl-for-ubuntu.zip
          asset_name: weatherdl-for-ubuntu.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            [Download for Windows](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-windows.zip)
            [Download for MacOS](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-macos.zip)
            [Download for Ubuntu](https://github.com/demccormack/weatherdl/releases/download/${{ github.ref_name }}/weatherdl-for-ubuntu.zip)
