name: CI

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Negotiate Python package hell
      run: sed -i '/python-magic-bin/d' requirements-prod.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-prod.txt -r requirements-dev.txt
    - name: Test
      run: pytest
    - name: Lint
      run: pylint $(git ls-files '*.py')
    - name: Format
      run: black . --check
