name: CI

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv sync --all-extras
    - name: Test
      run: uv run pytest
    - name: Lint
      run: uv run pylint $(git ls-files '*.py')
    - name: Format
      run: uv run black . --check
