name: CI Pipeline

on: 
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    needs: check
    uses: ./.github/workflows/build.yml

  test-releases:
    needs: build
    uses: ./.github/workflows/test-releases.yml

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test-releases
    uses: ./.github/workflows/release.yml
